title: Dr. Andrzej P. Kądzielawa
description: Andrzej P. Kądzielawa's homepage
author: Dr. Andrzej P. Kądzielawa
github: https://github.com/andrzejkadzielawa
about: Theoretical Physicist, HPC Specialist, and Professional Human
disqus_shortname: apkadzielawa
google_analytics: UA-130945943-1
avatar_url: /static/img/apk.png

enableTags: true
tagarray: []

collections:
  articles:
    output: true
    permalink: /acticles/:path/
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-github
      link: "https://github.com/andrzejkadzielawa"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/andrzej-k%C4%85dzielawa"
    - icon: fa-stack-exchange
      link: "mailto:apkadzielawa@gmail.com"
    - icon: fa-github
      link: "https://github.com/Mellechowicz"

urls:
    - text: Curriculum Vitae
      url: /cv/ 
    - text: Articles
      url: /articles/
    - text: Teaching
      url: /teaching.html
    - text: Conferences
      url: /projects/

url: "https://andrzejkadzielawa.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
